[package]
name = "day_7"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
strip = true
debug = false
lto = true
opt-level = 3
codegen-units = 1
